### ISSUE TITLE
Suggesting we work together on a project!

### ISSUE THREAD

**Issue by DanielRomeo** [mrbrianevans/automated-java-card-game#1]
Hi Brian, i'm daniel, i saw that you recently made an open source contribution on FOSSALGO, i have done so too a few weeks back.  was wondering if you would perhaps want us to also create a similar project where we mantain it and make it open for others to also contribute!? 

I'm sorry for having to make an issue on one of your projects in order to communicate with you. 

looking forward to hearing back from you!  
cheers

**Comment by mrbrianevans** [comment]
Hey Daniel,
Thanks for getting in touch. 
Yeah, that sounds good to me!
What sort of a project are you thinking of? 

And perhaps its better to email for communication. 
You can send me an email on brian@brianevans.tech

Cheers
